DROP TABLE NOTE;

CREATE TABLE NOTE
(
	NOTE_NUM			  INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE                 VARCHAR(500)  NOT NULL,
	CONTENT               VARCHAR(500)  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO NOTE (TITLE, CONTENT) VALUES ("title", "content");

COMMIT;	