DROP TABLE VOLUNTEER;

CREATE TABLE VOLUNTEER
(
	MEMBER_NUM			  INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRSTNAME             VARCHAR(50)  	NOT NULL,
	LASTNAME              VARCHAR(50)  	NOT NULL,
	BIRTH             	  DATE  			NULL,
	GENDER                VARCHAR(10)		NULL,
	UNIVERSITY            VARCHAR(50)  		NULL,
	MAJOR	              VARCHAR(50)  		NULL,
	EXPERTISE             VARCHAR(500)  	NULL,
	EXPERIENCE            VARCHAR(500)  	NULL,
	TEAM                  VARCHAR(50)  		NULL,
	COUNTRY               VARCHAR(50)  		NULL,
	ORGANISATION          VARCHAR(50)  		NULL,
	ROLE                  VARCHAR(50)  		NULL,
	EMAIL                 VARCHAR(50)  		NULL,
	IMG					  VARCHAR(500)  	NULL,
	YEAR				  VARCHAR(50)  		NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "MID-LONG", "Thailand", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "MID-LONG", "Thailand", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "MID-LONG", "Thailand", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "MID-LONG", "Thailand", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "HELLO", "Cambodia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "HELLO", "Cambodia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "HELLO", "Cambodia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "EE", "Cambodia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "EE", "Cambodia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "EE", "Indonesia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "EE", "Indonesia", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

INSERT INTO VOLUNTEER (FIRSTNAME, LASTNAME, BIRTH, GENDER, UNIVERSITY, MAJOR, EXPERTISE, EXPERIENCE, TEAM, COUNTRY, ORGANISATION, ROLE, EMAIL, IMG, YEAR) 
VALUES ("JINHEE", "LEE", "1990-03-12", "F", "SUNGSHIN", "IT", "X", "X", "EE", "Nepal", "ITU", "IT", "17and25@naver.com", "http://cfile10.uf.tistory.com/image/1957E0355084CB8038290B", "2016");

COMMIT;	