DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
	MEMBER_NUM			  INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRSTNAME             VARCHAR(50)  		NOT NULL,
	LASTNAME              VARCHAR(50)  		NOT NULL,
	BIRTH             	  DATE  			NULL,
	GENDER                VARCHAR(10)		NULL,
	UNIVERSITY            VARCHAR(50)  		NULL,
	MAJORCLASS	          VARCHAR(50)  		NULL,	
	MAJOR	              VARCHAR(50)  		NULL,
	EXPERTISE             VARCHAR(500)  	NULL,
	EXPERIENCE            VARCHAR(500)  	NULL,
	TEAM                  VARCHAR(50)  		NULL,
	COUNTRY               VARCHAR(50)  		NULL,
	ORG			          VARCHAR(50)  		NULL,
	ROLE                  VARCHAR(50)  		NULL,
	EMAIL                 VARCHAR(50)  		NULL,
	LINK				  VARCHAR(500)  	NULL,
	YEAR				  VARCHAR(50)  		NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

COMMIT;