DROP TABLE MEMBER;
DROP TABLE TEAM;

CREATE TABLE TEAM
(
	NUMBER			  	INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME             	VARCHAR(50)  	  NULL,
	COUNTRY			    VARCHAR(50)       NULL,
	ORGANIZATION		VARCHAR(50)       NULL,
	YEAR                VARCHAR(10)		  NULL,
	INTRODUCE           VARCHAR(500)  	  NULL,
	MOVIE             	VARCHAR(500) 	  NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE MEMBER
(
	NUMBER			  	  INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRSTNAME             VARCHAR(50)  		NOT NULL,
	LASTNAME              VARCHAR(50)  		NOT NULL,
	BIRTH             	  DATE  			NULL,
	GENDER                VARCHAR(10)		NULL,
	UNIVERSITY            VARCHAR(50)  		NULL,
	MAJORCLASS	          VARCHAR(50)  		NULL,	
	MAJOR	              VARCHAR(50)  		NULL,
	EXPERTISE             VARCHAR(500)  	NULL,
	EXPERIENCE            VARCHAR(500)  	NULL,
	ROLE                  VARCHAR(50)  		NULL,
	EMAIL                 VARCHAR(50)  		NULL,
	IMAGE				  VARCHAR(500)  	NULL,
	TEAM_NUMBER           INT(100)  		UNSIGNED NOT NULL
	PASSWORD			  VARCHAR(500)  	NULL,
	PASSWORD_RENEW		  BOOLEAN			NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE BOOKMARK
(
	NUMBER			  	  INT(100) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LIKE_MEMBER_NUMBER    INT(100)  		NOT NULL,
	MEMBER_NUMBER         INT(100)  		NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

ALTER TABLE MEMBER ADD FOREIGN KEY (TEAM_NUM) REFERENCES TEAM(NUMBER) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;